export const data = [
    {
        studentName: "Arekanti Dilip kumar",
        lastLogin: "Last Login : 3 days ago",
        country: "United States of America",
        universityName: "Arizona State University",
        universityDetail: "MS in Computer Science and Data Analytics",
        intake: "Spring -2023",
        course: "Masters",
        submittedBy: "Santhral Doe",
        submittedDate: "12-02-2022",
    },
    {
        studentName: "Basil kamboh",
        lastLogin: "Last Login : 3 days ago",
        country: "Pakistan",
        universityName: "Arizona State University",
        universityDetail: "MS in Computer Science and Data Analytics",
        intake: "Spring -2023",
        course: "Masters",
        submittedBy: "Santhral Doe",
        submittedDate: "12-02-2022",
    },
    {
        studentName: "Arekanti Dilip kumar",
        lastLogin: "Last Login : 3 days ago",
        country: "India",
        universityName: "Arizona State University",
        universityDetail: "MS in Computer Science and Data Analytics",
        intake: "Spring -2023",
        course: "Masters",
        submittedBy: "Santhral Doe",
        submittedDate: "12-02-2022",
    },
    {
        studentName: "Arekanti Dilip kumar",
        lastLogin: "Last Login : 3 days ago",
        country: "Mexico",
        universityName: "Arizona State University",
        universityDetail: "MS in Computer Science and Data Analytics",
        intake: "Spring -2023",
        course: "Masters",
        submittedBy: "Santhral Doe",
        submittedDate: "12-02-2022",
    },
    {
        studentName: "Arekanti Dilip kumar",
        lastLogin: "Last Login : 3 days ago",
        country: "Mexico",
        universityName: "Arizona State University",
        universityDetail: "MS in Computer Science and Data Analytics",
        intake: "Spring -2023",
        course: "Masters",
        submittedBy: "Santhral Doe",
        submittedDate: "12-02-2022",
    }
];